DROP TABLE PG_NBA_SEASON if exists;
DROP TABLE PG_NBA_TEAM if exists;
DROP TABLE PG_NBA_PLAYER if exists;

CREATE TABLE PG_NBA_PLAYER (
    NBA_PLAYER_ID   INTEGER NOT NULL  PRIMARY KEY,
    PLAYER_ALIAS    VARCHAR(50) NOT NULL,
    FIRST_NAME      VARCHAR(50) NOT NULL,
    LAST_NAME       VARCHAR(50) NOT NULL,
    POSITION        VARCHAR(1)  NULL,
    FIRST_SEASON    VARCHAR(4)  NULL,
    LAST_SEASON     VARCHAR(4)  NULL,
    HEIGHT_FEET     NUMERIC     NOT NULL,
    HEIGHT_INCHES   NUMERIC     NOT NULL,
    WEIGHT          NUMERIC     NOT NULL,
    COLLEGE         VARCHAR(100) NULL
);

CREATE TABLE PG_NBA_TEAM (
    NBA_TEAM_ID     INTEGER NOT NULL  PRIMARY KEY,
    TEAM_ALIAS      VARCHAR(50) NOT NULL,
    LOCATION        VARCHAR(100) NOT NULL,
    TEAM_NAME       VARCHAR(100) NOT NULL,
    LEAGUE          VARCHAR(1) NOT NULL
);

CREATE TABLE PG_NBA_SEASON (
    NBA_SEASON_ID INTEGER NOT NULL PRIMARY KEY,
    NBA_PLAYER_ID INTEGER NOT NULL,
    NBA_TEAM_ID   INTEGER NOT NULL,
    SEASON         VARCHAR(4)  NOT NULL,
    GAME_PLAY      INTEGER     NOT NULL,
    MINUTE         INTEGER     NOT NULL,
    POINT          INTEGER     NOT NULL,
    OFF_REBOUND    INTEGER     NOT NULL,
    DEF_REBOUND    INTEGER     NOT NULL,
    REBOUND        INTEGER     NOT NULL,
    ASSIST         INTEGER     NOT NULL,
    STEAL          INTEGER     NOT NULL,
    BLOCK          INTEGER     NOT NULL,
    TURNOVER       INTEGER     NOT NULL,
    PF             INTEGER     NOT NULL,
    FG_ATTEMPT     INTEGER     NOT NULL,
    FG_MADE        INTEGER     NOT NULL,
    FT_ATTEMPT     INTEGER     NOT NULL,
    FT_MADE        INTEGER     NOT NULL,
    TP_ATTEMPT     INTEGER     NOT NULL,
    TP_MADE        INTEGER     NOT NULL,
    FOREIGN KEY (NBA_PLAYER_ID) REFERENCES PG_NBA_PLAYER(NBA_PLAYER_ID),
    FOREIGN KEY (NBA_TEAM_ID) REFERENCES PG_NBA_TEAM(NBA_TEAM_ID)
);

CREATE SEQUENCE SEQ_PG_NBA_PLAYER;
CREATE SEQUENCE SEQ_PG_NBA_TEAM;
CREATE SEQUENCE SEQ_PG_NBA_SEASON;
